<h1><?php $this->__('Store Locator'); ?></h1>
<div style="height:400px; width:100%; display: block;">
  <div id="map-canvas" ></div>
</div>
<div id="stores" style="margin-top: 12px;">
    <div class="form-group">
        <div class="col-sm-10">
          <input type="text" class="form-control input-text required-entry" name="zipcode" id="zipcode" placeholder="<?php echo $this->__('Enter ZipCode'); ?>" />
        </div>
    </div>
</div>
