<h1>Store Locator</h1>
<div style="height:400px; width:100%; display: block;">
  <div id="map-canvas" ></div>
</div>
<!-- <div class="zipcodeLocator grid_8">
	<div class="form-group grid_4">
        <div class="col-sm-10">
          <input type="text" class="form-control input-text required-entry" name="zipcode" id="zipcode" placeholder="Enter Zip Code">
        </div>
  	</div>
  	<div class="form-group grid_4"> 
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default" onclick="getStores();">Search</button>
        </div>
    </div>
</div> -->
<style>
  html, body, #map-canvas {
    height: 100%;
    margin: 0px;
    padding: 0px;
  }

  .zipcodeLocator {
  	padding: 10px;
  }
</style>
<script type="text/javascript">
function initialize() {
	var mapOptions = {
		zoom: 4,
		center: new google.maps.LatLng(37.09024, -95.712891),
		mapTypeId: 'roadmap'
	};

	var bounds = new google.maps.LatLngBounds();

	var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

	map.setTilt(45);

	new Ajax.Request('<?php echo Mage::getUrl("storelocator/index/stores"); ?>', {
			onSuccess: function(response) {
				var stores = JSON.parse(response.transport.response);
				console.log(stores);
				console.log(map);
				var marker, i;
				var infowindow = new google.maps.InfoWindow();

				for(i=0; i < stores.length; i++) {
					var longitude = String(stores[i].longitude);
					var latitude  = String(stores[i].latitude);
					
		            var myLatlng = new google.maps.LatLng(latitude, longitude);
		            bounds.extend(myLatlng);

		            marker = new google.maps.Marker({
			            position: myLatlng,
			            map: map,
			            title: String(stores[i].name)            
			        });

					google.maps.event.addListener(marker, 'click', (function(marker, i) {
						return function() {
						  infowindow.setContent(stores[i].name);
						  infowindow.open(map, marker);
						}
					})(marker, i));
				}

				map.fitBounds(bounds);
			}
	});

	// Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
    var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
        this.setZoom(14);
        google.maps.event.removeListener(boundsListener);
    });
}

function loadScript() {
  var script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyAEsXZMr4cGtydPkINR3ub_TAGhkECICuw' +
      '&callback=initialize';
  document.body.appendChild(script);
}

window.onload = loadScript;
</script>